<?xml version="1.0"?>
<package format="3">
  <name>thread_reconstruction</name>
  <version>0.0.1</version>
  <description>This package reconstructs suture thread.</description>

  <maintainer email="emmaymhuang@gmail.com">Emma Huang</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_python</build_type>
  </export>

  <exec_depend>ros2launch</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
</package>

<!-- <package format="2">
  <name>thread_reconstruction</name>
  <version>0.1.0</version>
  <description>
    This package reconstructs suture thread.
  </description>
  <maintainer email="njogleka@ucsd.edu">Neelay Joglekar</maintainer>
  <license>TODO</license>

  <url>TODO</url>
  <author>Neelay Joglekar</author>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>actionlib</depend>
  <depend>actionlib_msgs</depend>

  <build_depend>message_generation</build_depend>

  <exec_depend>message_runtime</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>message_filters</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
</package> -->